global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'deploy-ledger'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'deploy-ledger'
    static_configs:
      - targets: ['deploy-ledger:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']